Fix some test failures on windows
* `TestRelativeRepoAndModDirs` setting up relative paths might fail in
  windows like:

        Rel: can't make C:\Users\RUNNER~1\AppData\Local\Temp\TestRelativeRepoAndModDirs1928585117\001\changed-test-relative-paths relative to D:\a\go-changed-pkgs\go-changed-pkgs\cmd

* `TestErrorsWhenFailsToReadPackages` relies on `chmod` unix like
  behaviour where the executable bit on a directory means search ability
  of that directory. In windows this bit does nothing, so skip the test

* `TestErrorsWhenFailingToParseGoMod`,
  `TestErrorsWhenFailsToReadingGoMod` apparently Git lists files with
  `/` as the path separator (and not `\`) on Windows, and apparently
  this works just fine (I couldn't find from docs from Git explaining
  how/why this is done) but given all the other tests are passing I
  assume it's fine to just fix the test and we don't need to do any
  extra handling in the actual application. This fixes errors
  like:

    --- FAIL: TestErrorsWhenFailingToParseGoMod (2.69s)
        main_test.go:336:
                    Error Trace:	D:/a/go-changed-pkgs/go-changed-pkgs/cmd/main_test.go:336
                    Error:      	Error "getting changed packages: parsing mod file cmd/testdata/repo/go.mod at 52c050cadb125c642c7786e45dba2887d6e17ef2: cmd/testdata/repo/go.mod:1: unknown directive: THIS" does not contain "parsing mod file cmd\\testdata\\repo/go.mod at 52c050cadb125c642c7786e45dba2887d6e17ef2"
                    Test:       	TestErrorsWhenFailingToParseGoMod
    --- FAIL: TestErrorsWhenFailsToReadingGoMod (5.22s)
        main_test.go:324:
                    Error Trace:	D:/a/go-changed-pkgs/go-changed-pkgs/cmd/main_test.go:324
                    Error:      	Error "getting changed packages: reading cmd/testdata/repo/go.mod at cde94c447ef4192c4ce5fd5eb8bdad3e771cf352: running command: `git -C C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestErrorsWhenFailsToReadingGoMod3927317333\\001\\remove-go-mod show cde94c447ef4192c4ce5fd5eb8bdad3e771cf352:cmd/testdata/repo/go.mod`: exit status 128\nstderr: fatal: path 'cmd/testdata/repo/go.mod' does not exist in 'cde94c447ef4192c4ce5fd5eb8bdad3e771cf352'\n" does not contain "reading cmd\\testdata\\repo/go.mod"
                    Test:       	TestErrorsWhenFailsToReadingGoMod
    FAIL